spring.application.name=storeapi
spring.datasource.url=jdbc:postgresql://localhost:5432/store_aggregator
spring.datasource.username=postgres
spring.datasource.password=YOUR_PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true